# Generated by Django 5.2 on 2025-05-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_email_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='doktorgecici@test.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
